/** Fun facts that Byte the robot cat throws at the player.
 *  Every fact is written so a Year 10 or Year 11 student can enjoy it
 *  without any extra reading. */
export const FACTS: string[] = [
  'The word "bug" for a software fault got popular in 1947 when a real moth was found stuck inside the Harvard Mark II computer. The team taped it into the logbook.',
  'One byte is 8 bits, and 8 bits can store 256 different patterns. That is exactly why a colour channel in an image goes from 0 to 255.',
  'The first computer programmer was Ada Lovelace in the 1840s. She wrote an algorithm for a machine that was never actually built.',
  'Your phone charger is a tiny computer. Modern USB C chargers negotiate voltage with your phone using a real communication protocol.',
  'A hexadecimal digit is worth exactly 4 bits, so two hex digits make one byte. That is why colour codes look like #FF8800.',
  'The QWERTY keyboard layout was designed for mechanical typewriters, not for speed. We still use it because everyone already learned it.',
  'RAM forgets everything when the power goes off, so it is called volatile. Your SSD is non volatile, which is why your homework survives a restart.',
  'A binary search can find one name in a phone book of one million entries in about 20 steps, but only if the list is already sorted.',
  'The internet and the World Wide Web are not the same thing. The internet is the network of cables and routers, the web is one service that runs on top of it.',
  'Every device on a network has a MAC address burned in at the factory. The first half of it identifies the manufacturer.',
  'IPv4 has about 4.3 billion addresses. We ran out, so IPv6 was created with enough addresses to give every grain of sand on Earth billions of its own.',
  'A CPU with a 3 GHz clock ticks three thousand million times every second. In the time it takes you to blink it has ticked about 900 million times.',
  'Cache memory is tiny but incredibly fast. Checking cache is like checking your pocket, checking RAM is like walking to your bedroom, checking the hard drive is like driving to a shop.',
  'MP3 files sound almost the same as the original because lossy compression throws away sounds that human ears struggle to hear anyway.',
  'A PNG image uses lossless compression, so every single pixel comes back exactly as it was. A JPEG does not, which is why re saving a JPEG many times makes it look mushy.',
  'The Domain Name System is basically the phone book of the internet. It turns bbc.co.uk into an IP address so your router knows where to send the request.',
  'Denial of service attacks do not steal data. They just flood a server with so many requests that real users cannot get through.',
  'The word "algorithm" comes from the name of the Persian mathematician al Khwarizmi, who lived over 1200 years ago.',
  'A single emoji can take 4 bytes in UTF 8, while a plain letter like A takes only 1 byte.',
  'Bubble sort is easy to write but slow. Sorting one million items with it would take roughly a million million comparisons.',
  'Solid state drives have no moving parts, which is why laptops with an SSD survive being knocked off a desk far better than ones with a hard disk drive.',
  'The very first webcam was pointed at a coffee pot in Cambridge so researchers could see if it was worth walking to the kitchen.',
  'Two to the power of ten is 1024, which is very close to 1000. That near miss is the reason people argue about whether a kilobyte is 1000 or 1024 bytes.',
  'Compilers translate the whole program in one go and produce an executable. Interpreters translate line by line while the program runs.',
  'An embedded system is a computer built to do one job. Your microwave, your washing machine and traffic lights all contain one.',
  'Sound is stored by sampling. A CD takes 44100 samples every second, which is more than double the highest pitch humans can hear.',
  'The bit depth of audio decides how many volume levels each sample can have. 16 bit audio gives 65536 possible levels.',
  'Phishing emails succeed because they create panic. A message that says "your account closes in one hour" is designed to stop you thinking.',
  'The Data Protection Act means an organisation must not keep your personal data forever. It has to be deleted once it is no longer needed.',
  'A firewall inspects packets going in and out of a network and blocks anything that breaks the rules it was given.',
  'Encryption does not hide the fact you sent a message. It only makes the contents unreadable to anyone without the key.',
  'The Caesar cipher shifts each letter by a fixed amount. It has only 25 useful keys, so a computer cracks it instantly.',
  'A stack works like a pile of plates. The last plate you put on is the first one you take off, so it is called last in first out.',
  'Python was named after Monty Python, not the snake. Its creator wanted a name that was short and slightly mysterious.',
  'The pixel is the smallest unit of a bitmap image. The word is short for "picture element".',
  'Metadata is data about data. A photo stores the date, camera model, shutter speed and sometimes even the exact GPS location.',
  'Star topology is popular because if one cable fails only that one device drops off. In a full mesh every device connects to every other device.',
  'Fibre optic cable carries data as pulses of light, so it is immune to the electrical interference that affects copper cable.',
  'Wi Fi signals struggle with thick walls, water and metal. That is why the bathroom is often the worst room in the house for signal.',
  'The TCP part of TCP IP checks that every packet arrived and asks for a resend if one went missing.',
  'Latency is the delay before data starts moving, bandwidth is how much can move per second. A slow ping and a fast download are two different problems.',
  'Virtual memory uses part of the hard drive as pretend RAM. It stops programs crashing but it is far slower than real RAM.',
  'Defragmentation only helps magnetic hard disk drives. Running it on an SSD wastes write cycles and gives no speed benefit.',
  'A trace table is the exam way of being a debugger by hand. You write down every variable after every line.',
  'Boolean logic is named after George Boole, who published his system of logic in 1854, about 90 years before the first electronic computers.',
  'A NOT gate is the only logic gate in the GCSE course with just one input.',
  'The fetch decode execute cycle never stops while the computer is on. It runs billions of times per second, even when the screen looks still.',
  'The program counter holds the address of the next instruction, not the current one. That single detail is worth a mark in exams.',
  'Overclocking a CPU makes it run faster but hotter. Without extra cooling it will throttle itself or fail.',
  'More cores does not always mean faster. A program has to be written to split its work before extra cores help at all.',
  'The first 1 TB hard drive arrived in 2007. Today a memory card the size of a fingernail holds the same amount.',
  'Cloud storage is not magic. It is a computer owned by someone else in a data centre, connected to you through the internet.',
  'Data centres use huge amounts of electricity, and a large share of it goes on cooling rather than on computing.',
  'E waste is the fastest growing type of rubbish in the world. Old phones contain gold, silver and rare metals worth recovering.',
  'An IP address can change, a MAC address usually does not. This is why network engineers use both.',
  'HTTPS is just HTTP with encryption added. The padlock means the connection is private, not that the website is honest.',
  'SQL was invented in the 1970s and is still the standard way to ask a database for information.',
  'A primary key must be unique for every record. Two students can share a name but never a student ID.',
  'Validation checks that data is sensible, verification checks that it was entered correctly. Asking someone to type a password twice is verification.',
  'A syntax error stops the program running at all. A logic error lets it run happily while giving the wrong answer, which is far more dangerous.',
  'Test data comes in three flavours for the exam: normal, boundary and invalid. Boundary data is the value right at the edge of what is allowed.',
  'A subroutine that returns a value is called a function. One that just does a job and returns nothing is called a procedure.',
  'Local variables only exist inside their subroutine. This is a good thing because it stops distant parts of a program breaking each other.',
  'Linear search checks items one at a time. It is slow but it works on unsorted data, which binary search cannot do.',
  'Merge sort splits a list until each piece has one item, then merges pieces back together in order. It is much faster than bubble sort on big lists.',
  'Insertion sort is what most people do naturally when sorting a hand of playing cards.',
  'Abstraction means removing detail that does not matter. A tube map is a famous example because it ignores real distances and shows only connections.',
  'Decomposition means breaking a big problem into smaller problems. Every large program is built this way.',
  'The OCR Exam Reference Language is not a real programming language you can run. It exists so exam questions do not favour students who learned one particular language.',
  'In Python, indentation is not decoration. The spaces at the start of a line actually change what the program does.',
  'The equals sign in programming means "put this value in here". To compare two things you need a double equals.',
  'A while loop can run zero times if its condition is false at the start. A for loop runs a set number of times.',
  'Reading a file with "r" and writing with "w" are different worlds. Opening a file with "w" wipes everything already in it.',
  'Casting converts data from one type to another. Adding "5" and 5 in Python raises an error until you cast one of them.',
  'ASCII uses 7 bits and covers 128 characters. Unicode covers over 140000 characters, including every emoji you have ever sent.',
  'An image file size is roughly width times height times colour depth. Doubling both width and height makes the file four times bigger.',
  'A utility program does housekeeping rather than real work. Backup software, compression tools and antivirus are all utilities.',
  'The operating system is the middle manager of your computer. It handles memory, files, users, hardware and the interface, so applications do not have to.',
  'Penetration testing means paying someone to attack your own network so you can find the holes before criminals do.',
  'SQL injection works by typing database commands into a normal text box. Input validation is the fix.',
  'Social engineering hacks the human, not the computer. The strongest password in the world does not help if you tell someone what it is.',
];
